require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'

target 'RNInspector' do
  config = use_frameworks!

  use_react_native!(:path => config["reactNativePath"])

  pod 'IOSInspector'
end
